// 화면 전체가 함께 보는 상태와 DOM 참조.


export const state = {
  player: null,
  metadata: null,
  duration: 100,
  durationEstimated: true,
  userEditedRange: false,
  liveDurationAtLoad: null,
  liveLoadedAt: null,
  playerTimeOffset: 0,
  playerTimeOffsetReady: false,
  previewSeekTimer: null,
  jobTimer: null,
  jobId: null,
  segmentTimer: null,
  notifiedJobs: new Set(),
  library: { videos: [], shorts: [], lives: [] },
  libraryTab: "videos",
  // 선택 구간(초)과 타임라인이 보여주는 구간(초).
  range: { start: 0, end: 100 },
  view: { start: 0, end: 100 },
  playhead: 0,
  drag: null,
  // 라이브에서 "지금"과 "받을 수 있는 최신 지점"의 차이(초).
  liveEdgeDelay: 0,
  // 지금 화면에 올라온 영상과, 늦게 도착한 정보 응답을 걸러내기 위한 표시.
  loadedVideoId: null,
  metadataToken: 0,
};

export const el = {
  appVersion: document.querySelector("#appVersion"),
  ytDlpStatus: document.querySelector("#ytDlpStatus"),
  ffmpegStatus: document.querySelector("#ffmpegStatus"),
  urlInput: document.querySelector("#urlInput"),
  loadButton: document.querySelector("#loadButton"),
  cookieBrowser: document.querySelector("#cookieBrowser"),
  cookiesFile: document.querySelector("#cookiesFile"),
  openLoginButton: document.querySelector("#openLoginButton"),
  applyLoginButton: document.querySelector("#applyLoginButton"),
  closeBrowserButton: document.querySelector("#closeBrowserButton"),
  ytDlpPath: document.querySelector("#ytDlpPath"),
  outputDir: document.querySelector("#outputDir"),
  formatMode: document.querySelector("#formatMode"),
  qualityMode: document.querySelector("#qualityMode"),
  accurateCut: document.querySelector("#accurateCut"),
  startInput: document.querySelector("#startInput"),
  endInput: document.querySelector("#endInput"),
  selectionDuration: document.querySelector("#selectionDuration"),
  segmentSummary: document.querySelector("#segmentSummary"),
  liveFromStart: document.querySelector("#liveFromStart"),
  playSegmentButton: document.querySelector("#playSegmentButton"),
  playButton: document.querySelector("#playButton"),
  pauseButton: document.querySelector("#pauseButton"),
  markStartButton: document.querySelector("#markStartButton"),
  markEndButton: document.querySelector("#markEndButton"),
  nudgeStartBack: document.querySelector("#nudgeStartBack"),
  nudgeStartForward: document.querySelector("#nudgeStartForward"),
  nudgeEndBack: document.querySelector("#nudgeEndBack"),
  nudgeEndForward: document.querySelector("#nudgeEndForward"),
  downloadButton: document.querySelector("#downloadButton"),
  cancelButton: document.querySelector("#cancelButton"),
  liveHint: document.querySelector("#liveHint"),
  zoomInButton: document.querySelector("#zoomInButton"),
  zoomOutButton: document.querySelector("#zoomOutButton"),
  fitSelectionButton: document.querySelector("#fitSelectionButton"),
  viewAllButton: document.querySelector("#viewAllButton"),
  zoomLabel: document.querySelector("#zoomLabel"),
  miniJobPercent: document.querySelector("#miniJobPercent"),
  miniJobDetails: document.querySelector("#miniJobDetails"),
  miniJobProgressBar: document.querySelector("#miniJobProgressBar"),
  message: document.querySelector("#message"),
  durationLabel: document.querySelector("#durationLabel"),
  timelineTrack: document.querySelector("#timelineTrack"),
  timelineRuler: document.querySelector("#timelineRuler"),
  timelineMap: document.querySelector("#timelineMap"),
  timelineMapView: document.querySelector("#timelineMapView"),
  timelineMapSelection: document.querySelector("#timelineMapSelection"),
  tlSelection: document.querySelector("#tlSelection"),
  tlHandleStart: document.querySelector("#tlHandleStart"),
  tlHandleEnd: document.querySelector("#tlHandleEnd"),
  playhead: document.querySelector("#playhead"),
  playheadTime: document.querySelector("#playheadTime"),
  previewFrame: document.querySelector(".preview-frame"),
  previewEmpty: document.querySelector("#previewEmpty"),
  videoTitle: document.querySelector("#videoTitle"),
  videoMeta: document.querySelector("#videoMeta"),
  thumbnail: document.querySelector("#thumbnail"),
  loadLibraryButton: document.querySelector("#loadLibraryButton"),
  libraryList: document.querySelector("#libraryList"),
  libraryTabs: document.querySelectorAll("[data-library-tab]"),
  jobState: document.querySelector("#jobState"),
  openConsoleButton: document.querySelector("#openConsoleButton"),
  toastStack: document.querySelector("#toastStack"),
};
